// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.4";

// src/lib/mcp/tools/list-stores.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@3.0.4";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-stores.ts
var list_stores_default = defineTool({
  name: "list_stores",
  title: "Listar lojas",
  description: "Lista as lojas do Mercado Livre conectadas e a data da \xFAltima sincroniza\xE7\xE3o.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_args, ctx) => {
    const { data, error } = await supabaseForUser(ctx).from("stores").select("id, name, ml_seller_id, ml_nickname, last_sync_at").order("created_at");
    if (error) throw new ToolError(error.message);
    const stores = (data ?? []).map((s) => ({
      id: s.id,
      name: s.name,
      seller_id: s.ml_seller_id,
      nickname: s.ml_nickname,
      last_sync_at: s.last_sync_at
    }));
    return { content: [{ type: "text", text: JSON.stringify(stores) }], structuredContent: { stores } };
  }
});

// src/lib/mcp/tools/list-orders.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z } from "npm:zod@^3.25.76";
var list_orders_default = defineTool2({
  name: "list_orders",
  title: "Listar pedidos",
  description: "Lista pedidos de um per\xEDodo (datas yyyy-MM-dd), com valores, cliente e itens.",
  inputSchema: {
    from: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Data inicial (yyyy-MM-dd)."),
    to: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Data final inclusiva (yyyy-MM-dd)."),
    store_id: z.string().uuid().optional().describe("Filtrar por loja (opcional)."),
    limit: z.number().int().min(1).max(500).default(100).describe("M\xE1ximo de pedidos.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, store_id, limit }, ctx) => {
    let q = supabaseForUser(ctx).from("orders").select("id, ml_order_id, store_id, status, date_created, buyer_name, total_amount, amount_received, ml_fees, shipping_cost, order_items(title, quantity, unit_price, cost_price)").gte("date_created", `${from}T00:00:00-03:00`).lte("date_created", `${to}T23:59:59.999-03:00`).order("date_created", { ascending: false }).limit(limit);
    if (store_id) q = q.eq("store_id", store_id);
    const { data, error } = await q;
    if (error) throw new ToolError2(error.message);
    const orders = (data ?? []).map((o) => ({
      id: o.id,
      ml_order_id: o.ml_order_id,
      store_id: o.store_id,
      status: o.status,
      date_created: o.date_created,
      buyer_name: o.buyer_name,
      total_amount: Number(o.total_amount),
      amount_received: Number(o.amount_received ?? 0),
      ml_fees: Number(o.ml_fees ?? 0),
      shipping_cost: Number(o.shipping_cost ?? 0),
      items: (o.order_items ?? []).map((i) => ({
        title: i.title,
        quantity: i.quantity,
        unit_price: Number(i.unit_price),
        cost_price: Number(i.cost_price ?? 0)
      }))
    }));
    return { content: [{ type: "text", text: JSON.stringify(orders) }], structuredContent: { orders } };
  }
});

// src/lib/mcp/tools/sales-summary.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z2 } from "npm:zod@^3.25.76";
var EXCLUDED = ["cancelled", "refunded"];
var sales_summary_default = defineTool3({
  name: "sales_summary",
  title: "Resumo de vendas",
  description: "Calcula faturamento, recebido, custos, publicidade e lucro de um per\xEDodo (exclui cancelados).",
  inputSchema: {
    from: z2.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Data inicial (yyyy-MM-dd)."),
    to: z2.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Data final inclusiva (yyyy-MM-dd)."),
    store_id: z2.string().uuid().optional().describe("Filtrar por loja (opcional).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, store_id }, ctx) => {
    const sb = supabaseForUser(ctx);
    let oq = sb.from("orders").select("status, total_amount, amount_received, ml_fees, shipping_cost, order_items(quantity, cost_price)").gte("date_created", `${from}T00:00:00-03:00`).lte("date_created", `${to}T23:59:59.999-03:00`).limit(1e4);
    if (store_id) oq = oq.eq("store_id", store_id);
    let aq = sb.from("ad_spend").select("amount").gte("charge_date", from).lte("charge_date", to);
    if (store_id) aq = aq.eq("store_id", store_id);
    const [{ data: orders, error: oe }, { data: ads, error: ae }] = await Promise.all([oq, aq]);
    if (oe) throw new ToolError3(oe.message);
    if (ae) throw new ToolError3(ae.message);
    const valid = (orders ?? []).filter((o) => !EXCLUDED.includes(o.status));
    let revenue = 0, received = 0, fees = 0, shipping = 0, cost = 0;
    for (const o of valid) {
      revenue += Number(o.total_amount);
      received += Number(o.amount_received ?? 0);
      fees += Number(o.ml_fees ?? 0);
      shipping += Number(o.shipping_cost ?? 0);
      for (const i of o.order_items ?? []) cost += Number(i.cost_price ?? 0) * i.quantity;
    }
    const advertising = (ads ?? []).reduce((a, r) => a + Number(r.amount), 0);
    const profit = received - cost - advertising;
    const r22 = (n) => Math.round(n * 100) / 100;
    const summary = {
      orders: valid.length,
      revenue: r22(revenue),
      received: r22(received),
      ml_fees: r22(fees),
      shipping: r22(shipping),
      product_cost: r22(cost),
      advertising: r22(advertising),
      profit: r22(profit),
      margin_pct: revenue ? r22(profit / revenue * 100) : 0,
      note: "Custos adicionais da aba 'Custos Adicionais' n\xE3o est\xE3o inclu\xEDdos."
    };
    return { content: [{ type: "text", text: JSON.stringify(summary) }], structuredContent: { summary } };
  }
});

// src/lib/mcp/tools/cash-profit-summary.ts
import { defineTool as defineTool4, ToolError as ToolError4 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z3 } from "npm:zod@^3.25.76";
var BRT_OFFSET_MS = 3 * 36e5;
var toBrtDate = (iso) => new Date(new Date(iso).getTime() - BRT_OFFSET_MS).toISOString().slice(0, 10);
var addDays = (ymd, n) => {
  const d = /* @__PURE__ */ new Date(ymd + "T12:00:00Z");
  d.setUTCDate(d.getUTCDate() + n);
  return d.toISOString().slice(0, 10);
};
var estimateDays = (storeName) => /edua/i.test(storeName) ? 30 : 15;
var r2 = (n) => Math.round(n * 100) / 100;
var cash_profit_summary_default = defineTool4({
  name: "cash_profit_summary",
  title: "Lucro em caixa do m\xEAs",
  description: "Vis\xE3o de fluxo de caixa: lucro (recebido \u2212 custo) de cada venda contado na data de libera\xE7\xE3o do Mercado Pago, entre 'from' e 'to'. Retorna o que j\xE1 caiu, o que ainda vai cair, o que fica para depois do per\xEDodo, publicidade, custos adicionais (fixos proporcionais aos dias) e a sobra para gastar.",
  inputSchema: {
    from: z3.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Data inicial de libera\xE7\xE3o (yyyy-MM-dd)."),
    to: z3.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Data final inclusiva de libera\xE7\xE3o (yyyy-MM-dd)."),
    store_id: z3.string().uuid().optional().describe("Filtrar por loja (opcional; omita para todas)."),
    include_orders: z3.boolean().default(false).describe("Incluir a lista de pedidos por data de libera\xE7\xE3o (opcional).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, store_id, include_orders }, ctx) => {
    if (from > to) throw new ToolError4("'from' deve ser anterior ou igual a 'to'.");
    const sb = supabaseForUser(ctx);
    const monthStart = from;
    const monthEnd = to;
    const periodDays = Math.round((Date.parse(to) - Date.parse(from)) / 864e5) + 1;
    const lookback = new Date(Date.parse(from + "T00:00:00Z") - 75 * 864e5).toISOString();
    let storesQ = sb.from("stores").select("id, name");
    let ordersQ = sb.from("orders").select("id, ml_order_id, store_id, date_created, status, amount_received, order_items(quantity, cost_price)").gte("date_created", lookback).not("status", "in", "(cancelled,refunded)");
    let relQ = sb.from("payments_releases").select("order_db_id, money_release_date, money_release_status").not("order_db_id", "is", null);
    let adsQ = sb.from("ad_spend").select("amount").gte("charge_date", monthStart).lte("charge_date", monthEnd);
    if (store_id) {
      storesQ = storesQ.eq("id", store_id);
      ordersQ = ordersQ.eq("store_id", store_id);
      relQ = relQ.eq("store_id", store_id);
      adsQ = adsQ.eq("store_id", store_id);
    }
    const costsQ = sb.from("additional_costs").select("amount, cost_type, cost_date");
    const [st, od, rl, ad, ac] = await Promise.all([storesQ, ordersQ.limit(5e3), relQ.limit(1e4), adsQ, costsQ]);
    for (const r of [st, od, rl, ad, ac]) if (r.error) throw new ToolError4(r.error.message);
    const storeName = new Map((st.data ?? []).map((s) => [s.id, s.name]));
    const relByOrder = /* @__PURE__ */ new Map();
    for (const r of rl.data ?? []) {
      if (!r.money_release_date) continue;
      const date = toBrtDate(r.money_release_date);
      const prev = relByOrder.get(r.order_db_id);
      if (!prev || date > prev.date) relByOrder.set(r.order_db_id, { date, released: r.money_release_status === "released" });
    }
    const today = toBrtDate((/* @__PURE__ */ new Date()).toISOString());
    const all = (od.data ?? []).map((o) => {
      const name = storeName.get(o.store_id) ?? "\u2014";
      const received = Number(o.amount_received ?? 0);
      const cost = (o.order_items ?? []).reduce((s, i) => s + Number(i.cost_price ?? 0) * Number(i.quantity ?? 1), 0);
      const rel = relByOrder.get(o.id);
      const release_date = rel?.date ?? addDays(toBrtDate(o.date_created), estimateDays(name));
      return {
        ml_order_id: o.ml_order_id,
        store: name,
        sale_date: toBrtDate(o.date_created),
        received: r2(received),
        cost: r2(cost),
        profit: r2(received - cost),
        release_date,
        confirmed: !!rel,
        released: rel ? rel.released || release_date <= today : false
      };
    });
    const inMonth = all.filter((o) => o.release_date >= monthStart && o.release_date <= monthEnd).sort((a, b) => a.release_date.localeCompare(b.release_date));
    const next = all.filter((o) => o.release_date > monthEnd && o.sale_date <= monthEnd);
    const sum = (a) => a.reduce((s, o) => s + o.profit, 0);
    const advertising = (ad.data ?? []).reduce((s, a) => s + Number(a.amount ?? 0), 0);
    const additional = (ac.data ?? []).reduce((s, c) => {
      if (c.cost_type === "fixed") return s + Number(c.amount ?? 0) * periodDays / 30;
      return c.cost_date >= monthStart && c.cost_date <= monthEnd ? s + Number(c.amount ?? 0) : s;
    }, 0);
    const total = sum(inMonth);
    const summary = {
      from,
      to,
      today,
      orders_in_period: inMonth.length,
      total_cash_profit: r2(total),
      already_released: r2(sum(inMonth.filter((o) => o.released))),
      pending_release: r2(sum(inMonth.filter((o) => !o.released))),
      after_period_retained: r2(sum(next)),
      after_period_orders: next.length,
      advertising: r2(advertising),
      additional_costs: r2(additional),
      net_cash_left: r2(total - advertising - additional),
      ...include_orders ? { orders: inMonth } : {}
    };
    return { content: [{ type: "text", text: JSON.stringify(summary) }], structuredContent: { summary } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "bulaobebfuruerltzbbe";
var mcp_default = defineMcp({
  name: "erp-valora-meli",
  title: "ERP Valora Meli",
  version: "0.1.0",
  instructions: "ERP de vendas das lojas do Mercado Livre. Use `list_stores` para ver as lojas, `list_orders` para pedidos de um per\xEDodo e `sales_summary` para faturamento, custos e lucro (compet\xEAncia), e `cash_profit_summary` para o lucro em caixa do m\xEAs (j\xE1 caiu, vai cair, sobra). Datas em yyyy-MM-dd, fuso de Bras\xEDlia.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_stores_default, list_orders_default, sales_summary_default, cash_profit_summary_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
